# Reference material: 
# https://github.com/rich-iannone/DiagrammeR#using-data-frames-to-define-graphviz-graphs

library(DiagrammeR) 
library(magrittr)

#Read in the IP data from the CSV generated by Wireshark
netDat <- read.csv("D:/coding/R/NetworkGraph/zeroaccess2.csv", sep=",", header=TRUE)

# Create the node data frame
nodes_df <- create_nodes(nodes = unique(c(netDat$Source,
                                          netDat$Destination)),
                         label = FALSE)

# The edge data frame must have columns named 'from' and 'to'
edges_df <- create_edges(from = netDat$Source,
                         to = netDat$Destination,
                         color = "red")

# Set the graph diagram's default attributes for...

# ...nodes
node_attrs <- c("style = filled", "fillcolor = lightgreen",
                "color = black", "shape = circle", "fontname = helvetica",
                "width = 1")

# ...edges
edge_attrs <- c("arrowhead = twopi", "color = black")

# ...and the graph itself
graph_attrs <- c("layout = twopi",
                 "overlap = false",
                 "fixedsize = false",
                 "ranksep = 3",
                 "outputorder = edgesfirst")

# Generate the graph diagram in the RStudio Viewer.
create_graph(nodes_df = nodes_df, edges_df = edges_df,
             graph_attrs = graph_attrs, node_attrs = node_attrs,
             edge_attrs = edge_attrs, directed = TRUE) %>%
 # render_graph(width = 1200, height = 800)
  render_graph()
